### ISSUE TITLE
Not working on latest MagicMirror

### ISSUE THREAD

**Issue by 82MHz** [nixnuex/MMM-iCal-ToDo#1]
I tried this module on the latest MagicMirror version, but it only leads to a black screen. Even on a minimal config.js file with only this module in the most basic configuration according to the readme, nothing shows up.

**Comment by nixnuex** [comment]
Fixed in v1.1.0. Please install dependencies as depicted in README.

**Comment by 82MHz** [comment]
Works like a charm, thank you very much for the fix!
